[2023-09-08T14:01:46.373+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artis_revenue.insert_into_dwh manual__2023-09-08T14:01:44.967379+00:00 [queued]>
[2023-09-08T14:01:46.381+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artis_revenue.insert_into_dwh manual__2023-09-08T14:01:44.967379+00:00 [queued]>
[2023-09-08T14:01:46.382+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-09-08T14:01:46.394+0000] {taskinstance.py:1382} INFO - Executing <Task(CreateTableIfNotExist): insert_into_dwh> on 2023-09-08 14:01:44.967379+00:00
[2023-09-08T14:01:46.400+0000] {standard_task_runner.py:57} INFO - Started process 330 to run task
[2023-09-08T14:01:46.403+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'artis_revenue', 'insert_into_dwh', 'manual__2023-09-08T14:01:44.967379+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/artist_revenue.py', '--cfg-path', '/tmp/tmppe_jdjp8']
[2023-09-08T14:01:46.405+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask insert_into_dwh
[2023-09-08T14:01:46.444+0000] {task_command.py:415} INFO - Running <TaskInstance: artis_revenue.insert_into_dwh manual__2023-09-08T14:01:44.967379+00:00 [running]> on host 80a7ead3f1b6
[2023-09-08T14:01:46.501+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aditiya Rahman' AIRFLOW_CTX_DAG_ID='artis_revenue' AIRFLOW_CTX_TASK_ID='insert_into_dwh' AIRFLOW_CTX_EXECUTION_DATE='2023-09-08T14:01:44.967379+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-08T14:01:44.967379+00:00'
[2023-09-08T14:01:46.502+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/create_table_operator.py", line 24, in execute
    source_hook.run(self.query)
AttributeError: 'CreateTableIfNotExist' object has no attribute 'query'
[2023-09-08T14:01:46.510+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=artis_revenue, task_id=insert_into_dwh, execution_date=20230908T140144, start_date=20230908T140146, end_date=20230908T140146
[2023-09-08T14:01:46.522+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 49 for task insert_into_dwh ('CreateTableIfNotExist' object has no attribute 'query'; 330)
[2023-09-08T14:01:46.535+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-08T14:01:46.548+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
